import argparse
import logging
from pathlib import Path
from typing import Optional, Union
import pandas as pd

from finetune.config import Config
from composereward import compose_reward
from mappkl2sig import generate_filtered_map_signals

logger = logging.getLogger(__name__)


def _default_paths(run_id: Optional[str] = None) -> dict[str, Path]:
    """Return default locations.

    Behavior:
    - If `run_id` is provided, do NOT load `Config`. Instead assume backtest
      outputs live under `outputs/backtest_results/finetune_backtest_demo_{run_id}`.
    - If `run_id` is None, load `Config()` and use its `backtest_result_path`
      and `backtest_save_folder_name` (legacy behavior).
    """
    base_dir = Path(__file__).resolve().parent
    if run_id:
        backtest_dir = Path("outputs") / "backtest_results" / f"finetune_backtest_demo_{run_id}"
        rid = run_id
    else:
        cfg = Config()
        backtest_dir = Path(cfg.backtest_result_path) / cfg.backtest_save_folder_name
        rid = cfg.run_id

    return {
        "backtest_dir": backtest_dir,
        "pred": backtest_dir / "predictions.pkl",
        "maps": backtest_dir / f"mapsignals_{rid}.npy",
        "stock_pool": base_dir / "dtstockdict.npy",
        "all_data": base_dir / "dtprice_stdict.npy",
        "all_signals": base_dir / "mapsignals.npy",
        "stock_real": base_dir / "dtstockdict.npy",
        "stock_hy_all": base_dir / "stockhyalldict.npy",
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Filter predictions -> mapsignals -> compose reward summary"
    )

    # Shared / filtering arguments
    parser.add_argument("--run-id", default=None, type=str,
                        help="Run id used for naming outputs; if not set, Config.run_id will be used")
    parser.add_argument("--pred-path", default=None, type=str,
                        help="Path to predictions.pkl generated by qlib_test (defaults based on run-id)")
    parser.add_argument("--stock-pool-path", default=None, type=str,
                        help="Path to stock pool npy (dtstockdict.npy); defaults next to this script")
    parser.add_argument("--map-output", default=None, type=str,
                        help="Output path for filtered mapsignals npy; defaults to backtest folder using run-id")
    parser.add_argument("--signal-key", default="last", type=str,
                        help="Key inside predictions.pkl to use (e.g., last, mean)")
    parser.add_argument("--nan-threshold", default=0.5, type=float,
                        help="Drop dates whose NaN ratio exceeds this value")
    parser.add_argument("--skip-filter", action="store_true",
                        help="Skip generating mapsignals and reuse existing file")
    parser.add_argument("--skip-existing", action="store_true",
                        help="Skip processing if output files already exist")

    # Compose reward arguments
    parser.add_argument("--chip", default=5, type=int, help="Initial chip count")
    parser.add_argument("--inter", default=3, type=int, choices=[2, 3, 5, 10, 15],
                        help="Holding interval threshold")
    parser.add_argument("--thres-step", default=0.2, type=float,
                        help="Step size for buy threshold search")
    parser.add_argument("--all-data-file", default=None, type=str,
                        help="Path to dtprice_stdict.npy (defaults next to this script)")
    parser.add_argument("--stock-real-dict-file", default=None, type=str,
                        help="Path to dtstockdict.npy (defaults next to this script)")
    parser.add_argument("--stock-hy-all-dict-file", default=None, type=str,
                        help="Path to stockhyalldict.npy (defaults next to this script)")
    parser.add_argument("--skip-compose", action="store_true",
                        help="Skip compose_reward stage")
    parser.add_argument("--reward-csv", default=None, type=str,
                        help="Optional path to save compose_reward result as CSV")
    parser.add_argument("--log-file", default=None, type=str,
                        help="Path to log file (default: kronostest_<run-id>.log under backtest folder)")

    return parser.parse_args()


def configure_logging(log_file: Optional[Union[str, Path]] = None) -> None:
    log_path = Path(log_file) if log_file else Path(__file__).with_name("kronostest.log")
    root_logger = logging.getLogger()

    # Allow changing log target between successive invocations (e.g., in run_kronos_batch).
    if root_logger.handlers:
        same_file = all(
            isinstance(h, logging.FileHandler) and Path(getattr(h, "baseFilename", "")) == log_path
            for h in root_logger.handlers
        )
        if same_file:
            return
        for h in root_logger.handlers[:]:
            root_logger.removeHandler(h)
            try:
                h.close()
            except Exception:
                pass

    log_path.parent.mkdir(parents=True, exist_ok=True)
    with open(log_path, "w", encoding="utf-8"):
        pass
    formatter = logging.Formatter("%(asctime)s [%(levelname)s] %(name)s - %(message)s")
    file_handler = logging.FileHandler(log_path, mode="a", encoding="utf-8")
    file_handler.setFormatter(formatter)
    logging.basicConfig(level=logging.INFO, handlers=[file_handler])


def _with_suffix(path: Path, suffix: str) -> Path:
    """Append suffix before file extension."""
    return path.with_name(f"{path.stem}_{suffix}{path.suffix}")


def run_kronos_test(
    run_id: Optional[str] = None,
    pred_path: Optional[Union[str, Path]] = None,
    stock_pool_path: Optional[Union[str, Path]] = None,
    map_output: Optional[Union[str, Path]] = None,
    signal_key: str = "last",
    nan_threshold: float = 0.5,
    skip_filter: bool = False,
    skip_existing: bool = False,
    chip: int = 5,
    inter: int = 3,
    thres_step: float = 0.2,
    all_data_file: Optional[Union[str, Path]] = None,
    stock_real_dict_file: Optional[Union[str, Path]] = None,
    stock_hy_all_dict_file: Optional[Union[str, Path]] = None,
    skip_compose: bool = False,
    reward_csv: Optional[Union[str, Path]] = None,
    log_file: Optional[Union[str, Path]] = None,
):
    """Orchestrate filtering and compose_reward with explicit parameters."""

    defaults = _default_paths(run_id)

    # Resolve run id from provided value or from defaults path (which embeds the run id)
    run_id = run_id or defaults["maps"].stem.replace("mapsignals_", "")
    # defaults was already computed with run_id in mind
    # If user didn't provide log_file, place it under the backtest results folder
    if log_file is None:
        log_file = defaults["backtest_dir"] / f"kronostest_{run_id}.log"

    configure_logging(log_file)

    # Default reward csv placed under backtest directory when not provided
    if reward_csv is None:
        reward_csv = defaults["backtest_dir"] / f"compose_reward_{run_id}.csv"

    pred_path = Path(pred_path) if pred_path else defaults["pred"]
    stock_pool_path = Path(stock_pool_path) if stock_pool_path else defaults["stock_pool"]
    base_signals_path = Path(map_output) if map_output else defaults["maps"]
    all_data_file = Path(all_data_file) if all_data_file else defaults["all_data"]
    stock_real_dict_file = Path(stock_real_dict_file) if stock_real_dict_file else defaults["stock_real"]
    stock_hy_all_dict_file = Path(stock_hy_all_dict_file) if stock_hy_all_dict_file else defaults["stock_hy_all"]

    signal_keys = ["last", "mean", "max", "min"] if signal_key == "all" else [signal_key]
    results = {}

    for sig in signal_keys:
        logger.info("\n===== SIGNAL %s START =====", sig)

        signals_path = _with_suffix(base_signals_path, sig) if len(signal_keys) > 1 else base_signals_path
        reward_csv_path = Path(reward_csv) if reward_csv else defaults["backtest_dir"] / f"compose_reward_{run_id}.csv"
        if len(signal_keys) > 1:
            reward_csv_path = _with_suffix(reward_csv_path, sig)
        summary_path = defaults["backtest_dir"] / (f"summary_{run_id}.txt" if len(signal_keys) == 1 else f"summary_{run_id}_{sig}.txt")

        # If a previous run already produced rewards, reuse them instead of recomputing.
        if skip_existing and reward_csv_path.is_file() and reward_csv_path.stat().st_size > 0:
            try:
                cached_df = pd.read_csv(reward_csv_path)
                logger.info("[Cache] Reusing existing compose_reward result for %s at %s", sig, reward_csv_path)
                summarize_reward(cached_df, summary_path=summary_path, signal=sig)
                results[sig] = cached_df
                continue
            except Exception as exc:
                logger.info("[Cache] Failed to load existing reward CSV %s (%s); recomputing.", reward_csv_path, exc)

        if not skip_filter:
            signals_path.parent.mkdir(parents=True, exist_ok=True)
            logger.info("[Step 1] Generating filtered map signals for %s...", sig)
            generate_filtered_map_signals(
                pred_path=str(pred_path),
                stock_pool_path=str(stock_pool_path),
                output_path=str(signals_path),
                signal_key=sig,
                nan_threshold=nan_threshold,
            )
        else:
            logger.info("[Step 1] Skipped filtering; reusing %s", signals_path)

        if skip_compose:
            logger.info("[Step 2] compose_reward skipped by flag")
            continue

        logger.info("[Step 2] Running compose_reward backtest for %s...", sig)
        reward_df = compose_reward(
            chip=chip,
            inter=inter,
            thres_step=thres_step,
            all_data_file=str(all_data_file),
            all_signals_file=str(signals_path),
            stock_real_dict_file=str(stock_real_dict_file),
            stock_hy_all_dict_file=str(stock_hy_all_dict_file),
        )

        # Append an average row across numeric metrics for quick comparison.
        if reward_df is not None and not reward_df.empty:
            numeric_cols = reward_df.select_dtypes(include="number").columns
            if len(numeric_cols):
                mean_values = reward_df[numeric_cols].mean()
                avg_row = {col: mean_values[col] for col in numeric_cols}
                if "modelname" in reward_df.columns:
                    avg_row["modelname"] = "avg"
                reward_df = pd.concat([reward_df, pd.DataFrame([avg_row])], ignore_index=True)

        summarize_reward(reward_df, summary_path=summary_path, signal=sig)

        if reward_csv_path and reward_df is not None and not reward_df.empty:
            reward_csv_path.parent.mkdir(parents=True, exist_ok=True)
            reward_df.to_csv(reward_csv_path, index=False)
            logger.info("Saved compose_reward result to %s", reward_csv_path)

        results[sig] = reward_df

    return results


def summarize_reward(df, summary_path: Optional[Union[str, Path]] = None, signal: str = "") -> None:
    if df is None or df.empty:
        logger.info("compose_reward returned no rows for signal %s", signal)
        if summary_path:
            Path(summary_path).parent.mkdir(parents=True, exist_ok=True)
            Path(summary_path).write_text("compose_reward returned no rows\n", encoding="utf-8")
        return

    df = df.reset_index(drop=True)
    best_row = df.sort_values("finalmoney", ascending=False).iloc[0]
    avg_row = df[df.get("modelname") == "avg"].iloc[0] if "modelname" in df.columns and "avg" in df.get("modelname", []) else None

    lines = []
    header = f"=== Reward Summary (signal={signal}) ===" if signal else "=== Reward Summary ==="
    lines.append(header)
    lines.append(df.to_string(index=False))
    lines.append(
        "Best setting: buythreshold={:.3f}, sellthreshold={}, finalmoney={:.2f}, maxhuiche={:.4f}, buyacc={:.4f}".format(
            best_row['buythreshold'],
            best_row['sellthreshold'],
            best_row['finalmoney'],
            best_row['maxhuiche'],
            best_row['buyacc'],
        )
    )
    if avg_row is not None:
        def _fmt(key):
            val = avg_row[key]
            if isinstance(val, float):
                return f"{val:.4f}" if abs(val) < 1000 else f"{val:.2f}"
            return str(val)
        lines.append(
            "Average (all rows): buythreshold={}, sellthreshold={}, finalmoney={}, maxhuiche={}, buyacc={}".format(
                _fmt('buythreshold'),
                _fmt('sellthreshold'),
                _fmt('finalmoney'),
                _fmt('maxhuiche'),
                _fmt('buyacc'),
            )
        )

    summary_text = "\n".join(lines)
    logger.info("\n%s", summary_text)
    if summary_path:
        summary_path = Path(summary_path)
        summary_path.parent.mkdir(parents=True, exist_ok=True)
        summary_path.write_text(summary_text + "\n", encoding="utf-8")


def main() -> None:
    args = parse_args()

    run_kronos_test(
        run_id=args.run_id,
        pred_path=args.pred_path,
        stock_pool_path=args.stock_pool_path,
        map_output=args.map_output,
        signal_key=args.signal_key,
        nan_threshold=args.nan_threshold,
        skip_filter=args.skip_filter,
        chip=args.chip,
        inter=args.inter,
        thres_step=args.thres_step,
        all_data_file=args.all_data_file,
        stock_real_dict_file=args.stock_real_dict_file,
        stock_hy_all_dict_file=args.stock_hy_all_dict_file,
        skip_compose=args.skip_compose,
        reward_csv=args.reward_csv,
        log_file=args.log_file,
    )


if __name__ == "__main__":
    main()